### ISSUE TITLE
`orders` microservice

### ISSUE THREAD

**Issue by pgressa** [pgressa/oraclecloud-cloudnative#10]
https://github.com/pgressa/oraclecloud-cloudnative/tree/master/src/orders

**Comment by pgressa** [comment]
```

import org.springframework.boot.actuate.metrics.jdbc.DataSourcePoolMetrics;

DataSource ordersDS = dataSourceBuilder.build();
        DataSourcePoolMetadataProvider provider = dataSource -> new HikariDataSourcePoolMetadata((HikariDataSource) dataSource);
        new DataSourcePoolMetrics(ordersDS,provider,"orders_data_source",null).bindTo(registry);
        return ordersDS;
```

**Comment by pgressa** [comment]
No idea of https://github.com/oracle-quickstart/oci-cloudnative/blob/master/src/orders/src/main/java/mushop/orders/services/OrdersService.java
```
private ScheduledExecutorService cartDeleteExecutor = Executors.newScheduledThreadPool(5);
```

**Comment by pgressa** [comment]
When using `micronaut-oraclecloud-atp` it's not possible to use other datasource like h2 in test, it fails with Validation exception b/c of https://github.com/micronaut-projects/micronaut-oracle-cloud/blob/master/oraclecloud-atp/src/main/java/io/micronaut/oraclecloud/atp/jdbc/AutonomousDatabaseConfiguration.java#L36

There need's to be some conditional requirement that will allow to use different datasource.

**Comment by pgressa** [comment]
fixes for oraclecloud https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/161

**Comment by graemerocher** [comment]
> Removed DataSourceConfiguration, contains pool metrics we do not support?
> 
> ```
> 
> import org.springframework.boot.actuate.metrics.jdbc.DataSourcePoolMetrics;
> 
> DataSource ordersDS = dataSourceBuilder.build();
>         DataSourcePoolMetadataProvider provider = dataSource -> new HikariDataSourcePoolMetadata((HikariDataSource) dataSource);
>         new DataSourcePoolMetrics(ordersDS,provider,"orders_data_source",null).bindTo(registry);
>         return ordersDS;
> ```

This is already registered here https://github.com/micronaut-projects/micronaut-sql/blob/64b604f75d2c9383eda98b5fc662f62056351831/jdbc-hikari/src/main/java/io/micronaut/configuration/jdbc/hikari/DatasourceFactory.java#L72-L84
