### ISSUE TITLE
`fulfillment` microservice 

### ISSUE THREAD

**Issue by pgressa** [pgressa/oraclecloud-cloudnative#8]
https://github.com/pgressa/oraclecloud-cloudnative/tree/master/src/fulfillment

**Comment by graemerocher** [comment]
This one is already in Micronaut? Probably needs upgrading at least

**Comment by graemerocher** [comment]
Seems it is suboptimal too and doesn't use our NATs module

**Comment by pgressa** [comment]
Yeah, I'll quickly optimise
